/**
 * Writes frontend/src/lib/deployments.ts from deployments.json, so the app, the
 * API routes, the patrol bot and the docs read ONE set of addresses.
 *   node tools/sync_addresses.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
const root = new URL("..", import.meta.url).pathname;
const d = JSON.parse(readFileSync(root + "deployments.json", "utf8"));
const c = d.contracts;
const out = `// Generated by tools/sync_addresses.mjs from deployments.json. Do not edit by hand.
export const DEPLOYMENTS = {
  network: "${d.network}",
  chainId: ${d.chain_id},
  explorer: "${d.explorer.replace(/\/$/, "")}",
  version: "${d.version}",
  commit: "${c.Sentinel.commit}",
  sentinel: "${c.Sentinel.address}",
  demo: "${c.SentinelDemo.address}",
  consumer: "${c.SentinelConsumer.address}",
  deployedAt: "${c.Sentinel.deployed_at}",
} as const;
`;
writeFileSync(root + "frontend/src/lib/deployments.ts", out);
console.log(out);
