/**
 * Checks every FINAL BREACH on the canonical contract against the chain's own
 * RPC (not Blockscout, not the validators): the transaction's sender, recipient,
 * native value and decoded ERC-20 Transfer logs, against the clause it broke.
 * Writes docs/BREACHES.md.   STUDIO_RPC=<relay> node tools/verify_breaches.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
const root = new URL("..", import.meta.url).pathname;
const require = createRequire(root + "test/package.json");
const { createClient } = require("genlayer-js");
const { studioDevnet } = require("genlayer-js/chains");
const { rpc, receipt } = await import(root + "test/chainscan.mjs");
const relay = process.env.STUDIO_RPC;
const chain = relay ? { ...studioDevnet, rpcUrls: { ...studioDevnet.rpcUrls, default: { ...studioDevnet.rpcUrls.default, http: [relay] } } } : studioDevnet;
const client = createClient({ chain });
const dep = JSON.parse(readFileSync(root + "deployments.json", "utf8"));
const CAN = dep.contracts.Sentinel.address;
const view = async (fn, args) => { for (let i = 0; i < 6; i++) { try { const r = await client.readContract({ address: CAN, functionName: fn, args }); return JSON.parse(r); } catch { await new Promise((r) => setTimeout(r, 20_000)); } } throw new Error(fn); };
const all = [...(await view("get_challenges", [0, 100])).challenges, ...(await view("get_challenges", [100, 100])).challenges];
const breaches = all.filter((c) => c.status === "FINAL" && c.final.verdict === "BREACH").sort((a, b) => a.challenge_id - b.challenge_id);
const rows = [];
for (const c of breaches) {
  const tx = await rpc(c.chain, "eth_getTransactionByHash", [c.tx_hash]);
  const r = await receipt(c.chain, c.tx_hash);
  const blk = await rpc(c.chain, "eth_getBlockByNumber", [tx.blockNumber, false]);
  const w = c.wallet.toLowerCase();
  const clause = c.snapshot.clauses.find((x) => x.id === c.final.clause);
  const addrs = (clause.text.toLowerCase().match(/0x[0-9a-f]{40}/g) ?? []);
  const from = tx.from.toLowerCase(), to = (tx.to ?? "").toLowerCase(), value = BigInt(tx.value);
  const sentTokens = r.transfers.filter((t) => t.from === w);
  let fact = "", holds = false;
  const t = clause.text.toLowerCase();
  if (/never call/.test(t)) { holds = from === w && addrs.includes(to); fact = `sender ${from.slice(0, 8)}… called ${to}`; }
  else if (/only call/.test(t)) { holds = from === w && !addrs.includes(to); fact = `sender ${from.slice(0, 8)}… called ${to}, not the listed contract`; }
  else if (/never send more than ([\d.]+) eth/.test(t)) { const lim = Number(t.match(/never send more than ([\d.]+) eth/)[1]); holds = from === w && Number(value) / 1e18 > lim; fact = `sender ${from.slice(0, 8)}… sent ${Number(value) / 1e18} ETH (limit ${lim})`; }
  else if (/only send the stablecoins/.test(t)) { const bad = sentTokens.filter((x) => !addrs.includes(x.token)); holds = bad.length > 0; fact = `agent sent token ${bad.map((x) => x.token).join(", ") || "none"} (listed: USDT, USDC)`; }
  else if (/never move more than ([\d,]+) usdc/.test(t)) { const lim = Number(t.match(/never move more than ([\d,]+) usdc/)[1].split(",").join("")); const amt = Math.max(0, ...sentTokens.map((x) => Number(x.value) / 1e6)); holds = from === w && amt > lim; fact = `agent sent ${amt} USDC in one transfer (limit ${lim})`; }
  else fact = "clause shape not checked by this tool";
  rows.push({ id: c.challenge_id, chain: c.chain, tx: c.tx_hash, clause: c.final.clause, severity: c.final.severity, by: c.challenger, status: r.status, ts: parseInt(blk.timestamp, 16), filedTs: c.tx_timestamp, fact, holds, slash: c.final.slash });
  console.log(`#${c.challenge_id} ${c.final.clause} ${c.final.severity} ${holds ? "CONFIRMED" : "NOT CONFIRMED"} — ${fact}`);
}
const BS = { ethereum: "eth.blockscout.com", base: "base.blockscout.com", arbitrum: "arbitrum.blockscout.com", polygon: "polygon.blockscout.com", robinhood: "robinhoodchain.blockscout.com" };
const md = `# Every final BREACH, checked by hand against the chain

Generated by \`tools/verify_breaches.mjs\` at ${new Date().toISOString()}: each transaction re-read from the chain's own public RPC (sender, recipient, native value, decoded ERC-20 \`Transfer\` logs, block time), independently of Blockscout and of the validators, and compared with the clause it was ruled to break. Canonical contract \`${CAN}\`.

**${rows.filter((r) => r.holds).length} of ${rows.length} confirmed.**

| Challenge | Chain | Transaction | Clause | Severity | Filed by | What the chain shows | Block time = filed | Confirmed |
|---|---|---|---|---|---|---|---|---|
${rows.map((r) => `| #${r.id} | ${r.chain} | [${r.tx.slice(0, 10)}…](https://${BS[r.chain]}/tx/${r.tx}) | ${r.clause} | ${r.severity} | ${r.by === "0x81d6bf84a5b03950d910b4a2f83c68006e0b93f4" ? "patrol bot" : r.by.slice(0, 8) + "…"} | ${r.fact} | ${r.ts === r.filedTs ? "yes" : "NO"} | ${r.holds ? "yes" : "**no**"} |`).join("\n")}

Several BREACH rulings on agent #0 slashed 0: its bond had already been taken to zero by earlier final breaches, and a slash is capped at the bond that is left.
`;
writeFileSync(root + "docs/BREACHES.md", md);
