// Generated by tools/sync_addresses.mjs from deployments.json. Do not edit by hand.
export const DEPLOYMENTS = {
  network: "studiodev",
  chainId: 61997,
  explorer: "https://explorer-studio-dev.genlayer.com",
  version: "2.0.0",
  commit: "1830a3458939937c60df85386b3a461332e611ca",
  sentinel: "0x41Ad5F63d1FeE9b63D2B6f8cD6C92dF08a64c0a2",
  demo: "0x0396d725d4a8D4F4E2BAC4Df1bc0BB80cbbC8e29",
  consumer: "0x02B793C1603fAa78997De8Cf2C6F370f205bDF83",
  deployedAt: "2026-10-08T14:47:53.168Z",
} as const;
