// Generated by tools/sync_addresses.mjs from deployments.json. Do not edit by hand.
export const DEPLOYMENTS = {
  network: "studiodev",
  chainId: 61997,
  explorer: "https://explorer-studio-dev.genlayer.com",
  version: "2.0.0",
  commit: "eae94e5af97161630ae6574305f428599c2505b0",
  sentinel: "0x92979f66ca6b3f6F57Ab2c6AD425DA68c9Ccb48D",
  demo: "0xc128B02839a6668ff9d9689214986864821CdC0b",
  consumer: "0xCcCc4495705bD11D47c2Cb0F719cD3B1630dc4b2",
  deployedAt: "2026-10-08T18:18:20.162Z",
} as const;
