// Generated by tools/sync_addresses.mjs from deployments.json. Do not edit by hand.
export const DEPLOYMENTS = {
  network: "studiodev",
  chainId: 61997,
  explorer: "https://explorer-studio-dev.genlayer.com",
  version: "2.0.0",
  commit: "bdca383329911eb5b40b9389899782b8c488723e",
  sentinel: "0x1d4B73BD37785F113a599505D80Bc9BDA3D96a90",
  demo: "0x5b30a2E64aA5C4a6089C5Df616EAac0d2e035393",
  consumer: "0x02F421486a6de07c3D2cF624576ED7ecDFe711e5",
  deployedAt: "2026-10-08T18:22:48.400Z",
} as const;
